# IMU type - 
#   0 = Auto discover
#   1 = Null (used when data is provided from a remote IMU
#   2 = InvenSense MPU-9150
#   3 = STM L3GD20H + LSM303D
#   4 = STM L3GD20 + LSM303DLHC
#   5 = STM LSM9DS0
#   6 = STM LSM9DS1
#   7 = InvenSense MPU-9250
#   8 = STM L3GD20H + LSM303DLHC
#   9 = Bosch BMX055
#   10 = Bosch BNX055
imu_type: 2
imu_frame: imu_link
i2c_bus: 1 
i2c_slave_address: 104
# Fusion type type - 
#   0 - Null. Use if only sensor data required without fusion
#   1 - Kalman STATE4
#   2 - RTQF
fusion_type: 2

mpu9150:
# Gyro sample rate (between 5Hz and 1000Hz)
  gyro_accel_sample_rate: 50
# Compass sample rate (between 1Hz and 100Hz)
  compass_sample_rate: 25
# Gyro/accel low pass filter - 
#   0 - gyro: 256Hz, accel: 260Hz
#   1 - gyro: 188Hz, accel: 184Hz
#   2 - gyro: 98Hz, accel: 98Hz
#   3 - gyro: 42Hz, accel: 44Hz
#   4 - gyro: 20Hz, accel: 21Hz
#   5 - gyro: 10Hz, accel: 10Hz
#   6 - gyro: 5Hz, accel: 5Hz
  gyro_accel_low_pass_filter: 4
# Gyro full scale range - 
#   0  - +/- 250 degress per second
#   8  - +/- 500 degress per second
#   16 - +/- 1000 degress per second
#   24 - +/- 2000 degress per second
  gyro_full_scale_range: 16
# Accel full scale range - 
#   0  - +/- 2g
#   8  - +/- 4g
#   16 - +/- 8g
#   24 - +/- 16g
  accel_full_scale_range: 16

# Calibration
calib:
  compass_min: [-202.092590, -59.069691, -123.718163]
  compass_max: [114.406723, 190.922394, 72.443916]
  
  accel_min: [ -1.009923, -0.993623, -1.037044 ]
  accel_max: [ 0.998343, 0.989066, 0.973186 ]

